### ISSUE TITLE
How do you turn off the beep?

### ISSUE THREAD

**Issue by Daniel-Kobayashi** [kunkel321/AutoCorrect2#2]
How do you turn off the beep?

**Comment by kunkel321** [comment]
I suppose there are a lot of beeps, LOL.  
I recommend opening the code in some editor, then using the Ctrl+F find tool of the editor.  Search for "SoundBeep" in the AutoCorrect2.ahk code.  Keep clicking on "find next."

The startup/reload announcement, double-beep is this code:
```
;===============================================================================
; Startup anouncement.  Also beeps whenever HotString Helper appends an item.
SoundBeep(900, 250)
SoundBeep(1100, 200)
```
The beep after a DOuble CAp FIx is this line of code: 
`SoundBeep(800, 80) ; Case fix announcent`. 

And the announcement of an autocorrection is this code:
`SoundBeep(900, 60) ; Notification of replacement.`

It should be safe to comment-out, or even delete these lines of code.

Should we have an option near the top of the code to turn all these off?  Maybe: 
`UseSoundBeepAnnouncements := 1`
